App/urls.py
from App import views
from django.urls import path

app_name = "App"

urlpatterns = [
    path("", views.loginuser, name="login"),
    path("login/",views.loginuser, name="login"),
    path("register/", views.register, name="register"),
    path("index/", views.index, name="index"),
    path("create-resume/", views.create_resume, name="create-resume"),
    path("resume/", views.resume, name="resume"),
    path("srt-resume/", views.resumesrt, name="resume"),
    # path("upload_csv",views.upload_csv, name="upload_csv"),
    path("logout/",views.logoutuser, name="logout"),
    
]

RESUME_BUILDER/urls.py
# from django.contrib import admin
# from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]
from django.conf import settings
# from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

app_name = "App"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("App.urls", namespace='App')),
    
]
# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class createResume(models.Model):
    name=models.CharField(max_length=122)
    address=models.TextField(max_length=500)
    phone=models.CharField(max_length=12)
    email=models.CharField(max_length=122)
    aboutyou=models.TextField(max_length=1000)
    careerobj=models.TextField(max_length=500)
    ssc=models.CharField(max_length= 10)
    hsc=models.CharField(max_length= 10)
    college=models.CharField(max_length= 100)
    degree=models.CharField(max_length= 100)
    cgpa=models.CharField(max_length= 10)
    comname3=models.CharField(max_length=500,blank=True)
    j3sd=models.DateField(blank=True, null=True)
    j3ed=models.DateField(blank=True, null=True)
    positiondet3=models.TextField(max_length=500)
    comname2=models.CharField(max_length=500,blank=True)
    j2sd=models.DateField(blank=True, null=True)
    j2ed=models.DateField(blank=True, null=True)
    positiondet2=models.TextField(max_length=500)
    comname1=models.CharField(max_length=500,blank=True)
    j1sd=models.DateField(blank=True, null=True) 
    j1ed=models.DateField(blank=True, null=True)
    positiondet1=models.TextField(max_length=500)
    references=models.TextField(max_length=600)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    template=models.CharField(max_length=122)
        
    def __str__(self):
            return self.name

class RegisterForm(models.Model):
    username=models.CharField(max_length=122)
    email=models.CharField(max_length=122)
    password=models.CharField(max_length=122)
    
    def __str__(self):
        return self.username

App/forms.py
# import form class from django
from django import forms
from .models import createResume

# create a ModelForm
class Resumedata(forms.ModelForm):
	class Meta:
		model = createResume
		fields = ['name','address','phone','email','aboutyou','careerobj','ssc','hsc','college','degree','cgpa','j3sd','j3ed','positiondet3','j2sd','j2ed','positiondet2','j1sd','j1ed','positiondet1','references']

App/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import createResume
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.shortcuts import render

# Create your views here.

def loginuser(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        # check if user have entered login credentials
        User = authenticate(request, username=username, password=password)
        if User is not None:
            login(request, User)
            # A backend authenticated the credentials
            return redirect("/index/")
        else:
            # No backend authenticated the credentials
            return redirect("/login/")
    return render(request, "login.html")


def logoutuser(request):
    logout(request)
    return redirect("/login/")


def register(request):
    if request.method == "POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        password = request.POST.get("password")
        user = User.objects.create_user(
            username=username, email=email, password=password)
        user.save()
        return redirect("/")
    return render(request, "register.html")


def index(request):
    return render(request, "index.html")

def resumesrt(request):
    return render(request, "srt-resume.html")


def create_resume(request):
    if request.method == "POST":
        name = request.POST.get('fullname')
        address = request.POST.get('address')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        aboutyou = request.POST.get('aboutyou')
        careerobj = request.POST.get('careerobj')
        ssc=request.POST.get('ssc')
        hsc=request.POST.get('hsc')
        college=request.POST.get('college')
        degree=request.POST.get('degree')
        cgpa=request.POST.get('cgpa')
        comname3=request.POST.get('comname3')
        j3sd = request.POST.get('j3sd')
        j3ed = request.POST.get('j3ed')
        positiondet3 = request.POST.get('positiondet3')
        comname2=request.POST.get('comname2')
        j2sd = request.POST.get('j3sd')
        j2ed = request.POST.get('j3ed')
        positiondet2 = request.POST.get('positiondet2')
        comname1=request.POST.get('comname1')
        j1sd = request.POST.get('j1sd')
        j1ed = request.POST.get('j1ed')
        positiondet1 = request.POST.get('positiondet1')
        references = request.POST.get('references')
        user=request.user
        template="resume.html"
        print(11)
        create_resume = createResume(user=user,template=template,name=name,comname1=comname1,comname2=comname2,comname3=comname3, address=address, phone=phone, email=email, aboutyou=aboutyou, careerobj=careerobj, ssc=ssc, hsc=hsc, college=college, degree=degree, cgpa=cgpa, j3sd=j3sd,j3ed=j3ed, positiondet3=positiondet3, j2sd=j2sd, j2ed=j2ed, positiondet2=positiondet2, j1sd=j1sd, j1ed=j1ed, positiondet1=positiondet1, references=references)
        print(12)
        create_resume.save()
        messages.success(request, "Your Info has been saved")
    return render(request, "create-resume.html")

def resume(request):
    try:
        print("hello")
        resume_info = createResume.objects.filter(user = request.user).first()
        print(resume_info.__dict__)
        context = {"resume_info": resume_info}
        return render(request, "resume.html", context)
    except Exception as e:
        print(e)
        print("hello2")
        return render(request, "resume.html")

# def upload_csv(request):
#     if request.method=="POST":
#         print("Hello")
#     return render(request,"index.html")

App/templates/create-resume.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>Fauna Resume Builder</title>
    <link href="{% static './style.css' %}" rel="stylesheet" />
</head>

<body>
    <!-- partial:index.partial.html -->
    <div id="javascript_header">
    </div>
    <form action="{% url 'App:create-resume' %}" method="POST" enctype="multipart/form-data" class="form-horizontal">
        {% csrf_token %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %} style="color:red;">{{ message }}</li>
                {% endfor %}
        </ul>

        <div class="form__header">
            <h1>Build Your Resume</h1>
            <p>Enter the fields below to generate a resume file.</p>
        </div>
        <h2>Personal Details</h2>
        <div class="form-group">
            <label for="name">Full Name<span>*</span></label>
            <input id="name" name="fullname" value="{{resume_info.fullname}}" type="text" />
            <div class="error" id="name__error">
            </div>
        </div>

        <div class="form-group">
            <label for="address">Address</label>
            <input id="address" name="address" value="{{resume_info.address}}" type="text" />
        </div>

        <div class="form-group">
            <label for="phone">Phone</label>
            <input id="phone" name="phone" value="{{resume_info.phone}}" type="text" />
        </div>

        <div class="form-group">
            <label for="email">Email<span>*</span></label>
            <input id="email" name="email" value="{{resume_info.email}}" type="email" />
            <div class="error" id="email__error">
            </div>
        </div>
        <div class="form-group">
            <label for="about">About You</label>
            <textarea id="about" name="aboutyou" placeholder="{{resume_info.about_you}}"></textarea>
        </div>

        <div class="form-group">
            <label for="career">Career Objectives</label>
            <textarea id="career" name="careerobj" placeholder="{{resume_info.career}}"></textarea>
        </div>

        <div class="form-group">
            <label class="text-center" for="education">Education</label>

            <div class="line-break">
            </div>

            <label for="ssc">Enter your SSC marks(in %)</label>
            <input type="number" step="0.01" name="ssc" id="ssc" name="ssc" placeholder="{{resume_info.ssc}}">
            <label for="hsc">Enter your HSC marks(in %)</label>
            <input type="number" name="hsc" step="0.01" id="hsc" name="hsc" placeholder="{{resume_info.hsc}}">
            <label for="college">Enter your college name</label>
            <input type="text" name="college" id="collegename" name="college" placeholder="{{resume_info.college}}">
            <label for="degree">Enter the name of your degree</label>
            <input type="text" name="degree" id="degree" name="degree" placeholder="{{resume_info.degree}}">
            <label for="CGPA">Enter your CGPA</label>
            <input type="number" name="cgpa" step="0.01" id="cgpa" name="cgpa" placeholder="{{resume_info.cgpa}}">
        </div>

        <div class="line-break">
        </div>

        <h2>Work Experience</h2>
        <h3>Most Recent Job</h3>
        <div class="form-group">
            <label for="address">Company's Name</label>
            <input id="comname3" name="comname3" value="{{resume_info.comname3}}" type="text" />
        </div>
        <div class="form-date-group">
            <div class="form-group">
                <label for="job-1__start">Start Date</label>
                <input id="job-1__start" name="j3sd" value="{{resume_info.job_1__start}}" type="date" />
            </div>
            <div class="form-group">
                <label for="job-1__end">End Date</label>
                <input id="job-1__end" name="j3ed" value="{{resume_info.job_1__end}}" type="date" />
            </div>
        </div>
        <div class="form-group">
            <label for="job-1__details">Position Details</label>
            <textarea id="job-1__details" name="positiondet3" placeholder="{{resume_info.job_1__details}}"></textarea>
        </div>
        <div class="line-break">
        </div>
        <h3>Past Job</h3>

        <div class="form-date-group">
            <div class="form-group">
                <label for="address">Company's Name</label>
                <input id="comname2" name="comname2" value="{{resume_info.comname2}}" type="text" />
            </div>

            <div class="form-group">
                <label for="job-2__start">Start Date</label>
                <input id="job-2__start" name="j2sd" value="{{resume_info.job_2__start}}" type="date" />
            </div>
            <div class="form-group">
                <label for="job-2__end">End Date</label>
                <input id="job-2__end" name="j2ed" value="{{resume_info.job_2__end}}" type="date" />
            </div>
        </div>

        <div class="form-group">
            <label for="job-2__details">Position Details</label>
            <textarea id="job-2__details" name="positiondet2" placeholder="{{resume_info.job_2__details}}"></textarea>
        </div>
        <div class="line-break">
        </div>

        <h3>Another Past Job</h3>
        <div class="form-date-group">
            <div class="form-group">
                <label for="address">Company's Name</label>
                <input id="comname1" name="comname1" value="{{resume_info.comname1}}" type="text" />
            </div>

            <div class="form-group">
                <label for="job-3__start">Start Date</label>
                <input id="job-3__start" name="j1sd" value="{{resume_info.job_3__start}}" type="date" />
            </div>
            <div class="form-group">
                <label for="job-3__end">End Date</label>
                <input id="job-3__end" name="j1ed" value="{{resume_info.job_3__end}}" type="date" />
            </div>
        </div>
        <div class="form-group">
            <label for="job-3__details">Position Details</label>
            <textarea id="job-3__details" name="positiondet1" placeholder="{{resume_info.job_3__details}}"></textarea>
        </div>
        <div class="line-break">
        </div>
        <div class="form-group">
            <label for="references">References</label>
            <textarea id="references" name="references" placeholder="{{resume_info.references}}"></textarea>
        </div>
        <div class="line-break">
        </div>
        <input type="submit" value="Submit Info" />
        <br>
        <a class="button" style="background-color:red;" href="/index/">Back to home</a>
    </form>

    <!-- partial -->
    <script src="{% static './script.js' %}">
    </script>

</body>

</html>

App/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>Fauna Resume Builder</title>
    <link href="{% static './style.css' %}" rel="stylesheet" />
</head>

<body>
    <!-- partial:index.partial.html -->
    <div id="javascript_header">
    </div>
    <form action="POST">
        <div class="form__header">
            <h1>Build Your Resume</h1>
            <p>Dashboard</p>
        </div>
        <div class="line-break">
        </div>
        <a class="button" href="/create-resume/"> Create/Edit Resume</a>
        <div class="line-break">
        </div>
        <a class="button" href="/resume/"> View Resume</a>
        <div class="line-break">
        </div>
        <!-- <a class="button" style="background-color:red;" href="login"> Logout </a> -->
    </form>

    <!-- partial -->
    <script src="{% static './script.js' %}">
    </script>

</body>

</html>

App/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>
        Fauna Resume Builder
    </title>
    <link href="{% static './style.css' %}" rel="stylesheet" />
</head>

<body>
    <!-- partial:index.partial.html -->
    <div id="javascript_header">
    </div>
    <form method="POST" action="/login/">
        {% csrf_token %}
        <div class="form__header">
            <h1>Login/Sign In</h1>
            <p>Enter your login details below.</p>
            {% csrf_token %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}" {% endif %} style="color:red;">{{ message }}</li>
                    {% endfor %}
            </ul>
        </div>
        <div class="form-group">
            <label for="name">Username<span>*</span></label>
            <input id="username" name="username" type="text" />
            <div class="error" id="name__error">
            </div>
        </div>
        <div class="form-group">
            <label for="password">Password<span>*</span></label>
            <input id="password" name="password" type="password" />
        </div>
        <div class="line-break">
        </div>
        <input id="login" type="submit" value="Login" /> Don't have an account? <a href="/register/">Sign Up</a>
    </form>

    <!-- partial -->
    <script src="{% static './script.js' %}">
    </script>

</body>

</html>

App/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>
        Fauna Resume Builder
    </title>
    <link href="{% static './style.css' %}" rel="stylesheet" />
</head>

<body>
    <!-- partial:index.partial.html -->
    <div id="javascript_header">
    </div>
    <form method="POST">
        {% csrf_token %}
        <div class="form__header">
            <h1>Register/Sign Up</h1>
            <p>Enter your login details below.</p>
        </div>
        <div class="form-group">
            <label for="name">Username<span>*</span></label>
            <input id="username" name="username" type="text" />
            <div class="error" id="name__error">
            </div>
        </div>
        <div class="form-group">
            <label for="email">Email<span>*</span></label>
            <input id="email" name="email" type="email" />
            <div class="error" id="name__error">
            </div>
        </div>
        <div class="form-group">
            <label for="password">Password<span>*</span></label>
            <input id="password" name="password" type="password" />
        </div>
        <div class="line-break">
        </div>
        <input id="register" type="submit" value="Register" /> Already have an account? <a href="/login/">Sign In</a>
    </form>

    <!-- partial -->
    <script src="{% static './script.js' %}">
    </script>
</body>

</html>

App/templates/resume copy.html
<html>

<head>
    <title>{% if Resume_Info.full_name %}{{Resume_Info.full_name}}'s Resume {% endif %}</title>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Poppins:400,600&display=swap');
        body {
            font-family: 'Poppins', sans-serif;
            background: #fafafa;
            color: rgba(182, 3, 3, 0.75);
        }
        
        h1 {
            color: rgba(172, 12, 12, 0.9);
        }
        
        h1,
        p {
            box-sizing: border-box;
            margin: 0px;
            padding: 0px 24px;
        }
        
        .line-break {
            width: 100%;
            height: 1px;
            margin: 16px auto;
            border-bottom: 1px solid #eee;
        }
        
        .resume {
            border-radius: 8px;
            box-sizing: border-box;
            display: flex;
            flex-direction: column;
            max-width: 800px;
            margin: 48px auto;
            padding: 16px 0px;
            background: white;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.02), 0 1px 2px rgba(0, 0, 0, 0.14);
        }
        
        .resume-group {
            box-sizing: border-box;
            padding: 8px 0px;
            width: 100%;
            display: flex;
            border-left: 3px solid transparent;
            transition: 0.2s;
        }
        
        .resume-group:hover {
            border-left: 3px solid #520dc2;
        }
        
        .left-col {
            width: 35%;
        }
        
        .right-col {
            width: 65%;
        }
        
        .instructions {
            opacity: 0.5;
            text-align: center;
            font-size: 0.8rem;
            margin: 16px auto;
        }
    </style>
</head>

<body>
    <div class="resume">
        {% if Resume_Info.full_name %}
        <h1>{{Resume_Info.full_name}}</h1>

        {% endif %} {% if Resume_Info.email %}
        <p>{{Resume_Info.email}}</p>

        {% endif %} {% if Resume_Info.phone %}
        <p>{{Resume_Info.phone}}</p>

        {% endif %}{% if Resume_Info.address %}
        <p>{{Resume_Info.address}}</p>

        {% endif %}
        <div class="line-break"></div>
        {% if Resume_Info.about_you%}

        <div class="resume-group">
            <div class="left-col">
                <p>ABOUT ME</p>
            </div>
            <div class="right-col">
                <p>{{Resume_Info.about_you}}</p>
            </div>
        </div>

        {% endif %} {% if Resume_Info.career %}
        <div class="resume-group">
            <div class="left-col">
                <p>CAREER OBJECTIVES</p>
            </div>

            <div class="right-col">
                <p>{{Resume_Info.career}}</p>
            </div>
        </div>

        {% endif %} {% if Resume_Info.education %}
        <div class="resume-group">
            <div class="left-col">
                <p>EDUCATION</p>
            </div>
            <div class="right-col">
                <p>{{Resume_Info.education}}</p>
            </div>
        </div>

        {% endif %}
        <div class="resume-group">
            <div class="left-col">
                <p>EMPLOYMENT EXPERIENCE</p>
            </div>
            <div class="right-col">
                <p></p>
            </div>
        </div>

        {% if Resume_Info.job_1__start %}
        <div class="resume-group">
            <div class="left-col">
                <p>{{Resume_Info.job_1__start}} to {{Resume_Info.job_1__end}}</p>
            </div>
            <div class="right-col">
                <p>{{Resume_Info.job_1__details}}</p>
            </div>
        </div>

        {% endif %} {% if Resume_Info.job_2__start %}
        <div class="resume-group">
            <div class="left-col">
                <p>{{Resume_Info.job_2__start}} to {{Resume_Info.job_2__end}}</p>
            </div>
            <div class="right-col">
                <p>{{Resume_Info.job_2__details}}</p>
            </div>
        </div>

        {% endif %} {% if Resume_Info.job_3__start %}
        <div class="resume-group">
            <div class="left-col">
                <p>{{Resume_Info.job_3__start}} to {{Resume_Info.job_3__end}}</p>
            </div>
            <div class="right-col">
                <p>{{Resume_Info.job_3__details}}</p>
            </div>
        </div>


        {% endif %}
        <div class="resume-group">
            <div class="left-col">
                <p>REFERENCES</p>
            </div>
            <div class="right-col">
                <p>{% if Resume_Info.references %}{{Resume_Info.references}}{% else %}Available upon request{% endif %}</p>
            </div>
        </div>
    </div>
    <div class="instructions">Ctrl + P and "Save As PDF" to make a copy of this resume</div>

</body>

</html>

App/templates/resume.html
<html>

<head>
    <title>{% if resume_info.full_name %}{{resume_info.full_name}}'s Resume {% endif %}</title>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Poppins:400,600&display=swap');
        body {
            font-family: 'Poppins', sans-serif;
            background: #fafafa;
            color: rgba(0, 0, 0, 0.75);
        }
        
        h1 {
            color: rgba(0, 0, 0, 0.9);
        }
        
        h1,
        p {
            box-sizing: border-box;
            margin: 0px;
            padding: 0px 24px;
        }
        
        .line-break {
            width: 100%;
            height: 1px;
            margin: 16px auto;
            border-bottom: 1px solid #eee;
        }
        
        .resume {
            border-radius: 8px;
            box-sizing: border-box;
            display: flex;
            flex-direction: column;
            max-width: 800px;
            margin: 48px auto;
            padding: 16px 0px;
            background: white;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.02), 0 1px 2px rgba(0, 0, 0, 0.14);
        }
        
        .resume-group {
            box-sizing: border-box;
            padding: 8px 0px;
            width: 100%;
            display: flex;
            border-left: 3px solid transparent;
            transition: 0.2s;
        }
        
        .resume-group:hover {
            border-left: 3px solid #520dc2;
        }
        
        .left-col {
            width: 35%;
        }
        
        .right-col {
            width: 65%;
        }
        
        .instructions {
            opacity: 0.5;
            text-align: center;
            font-size: 0.8rem;
            margin: 16px auto;
        }
    </style>
</head>

<body>
    <div class="resume">

        {% if resume_info.name %}
        <p>{{resume_info.name}}</p>
        {% endif %} {% if resume_info.email %}
        <p>{{resume_info.email}}</p>

        {% endif %} {% if resume_info.phone %}
        <p>{{resume_info.phone}}</p>
        {% endif %}{% if resume_info.address %}
        <p>{{resume_info.address}}</p>

        {% endif %}
        <div class="line-break"></div>
        {% if resume_info.aboutyou%}

        <div class="resume-group">
            <div class="left-col">
                <p>ABOUT ME</p>
            </div>
            <div class="right-col">
                <p>{{resume_info.aboutyou}}</p>
            </div>
        </div>

        {% endif %} {% if resume_info.career %}
        <div class="resume-group">
            <div class="left-col">
                <p>CAREER OBJECTIVES</p>
            </div>

            <div class="right-col">
                <p>{{resume_info.career}}</p>
            </div>
        </div>

        {% endif %} {% if resume_info.ssc %}
        <div class="resume-group">
            <div class="left-col">
                <p>SSC</p>
            </div>
            <div class="right-col">
                <p>{{resume_info.ssc}}</p>
            </div>
        </div>

        {% endif %} {% if resume_info.hsc %}
        <div class="resume-group">
            <div class="left-col">
                <p>HSC</p>
            </div>
            <div class="right-col">
                <p>{{resume_info.hsc}}</p>
            </div>
        </div>
        {% endif %}
        <div class="resume-group">
            <div class="left-col">
                <p>EMPLOYMENT EXPERIENCE</p>
            </div>
            <div class="right-col">
                <p></p>
            </div>
        </div>

        {% if resume_info.j3sd %}
        <div class="resume-group">
            <div class="left-col">
                <p>{{resume_info.j3sd}} to {{resume_info.j3ed}}</p>
            </div>
            <div class="right-col">
                <p>{{resume_info.positiondet3}}</p>
            </div>
        </div>

        {% endif %} {% if resume_info.j2sd %}
        <div class="resume-group">
            <div class="left-col">
                <p>{{resume_info.j2sd}} to {{resume_info.j2ed}}</p>
            </div>
            <div class="right-col">
                <p>{{resume_info.positiondet2}}</p>
            </div>
        </div>

        {% endif %} {% if resume_info.j1sd %}
        <div class="resume-group">
            <div class="left-col">
                <p>{{resume_info.j1sd}} to {{resume_info.j1ed}}</p>
            </div>
            <div class="right-col">
                <p>{{resume_info.positiondet1}}</p>
            </div>
        </div>

        {% endif %}
        <div class="resume-group">
            <div class="left-col">
                <p>REFERENCES</p>
            </div>
            <div class="right-col">
                <p>{% if resume_info.references %}{{resume_info.references}}{% else %}Available upon request{% endif %}</p>
            </div>
        </div>
    </div>
    <div class="instructions">Ctrl + P and "Save As PDF" to make a copy of this resume</div>

</body>

</html>